export const ON_BLOGS_INITIAL_REQUEST = "ON_BLOGS_INITIAL_REQUEST";
export const ON_BLOGS_SUCESS = "ON_BLOGS_SUCESS";
export const ON_BLOGS_FAIL = "ON_BLOGS_FAIL";

export const ON_FETCH_ALL_INITIAL = "ON_FETCH_ALL_INITIAL";
export const ON_FETCH_ALL_SUCCESS = "ON_FETCH_ALL_SUCCESS";
export const ON_FETCH_ALL_FAIL = "ON_FETCH_ALL_FAIL";

export const ON_FETCH_ONE_INITIAL = "ON_FETCH_ONE_INITIAL";
export const ON_FETCH_ONE_SUCCESS = "ON_FETCH_ONE_SUCCESS";
export const ON_FETCH_ONE_FAIL = "ON_FETCH_ONE_FAIL";

export const ON_DELETE_INITIAL = "ON_DELETE_INITIAL";
export const ON_DELETE_SUCCESS = "ON_DELETE_SUCCESS";
export const ON_DELETE_FAIL = "ON_DELETE_FAIL";

export const ON_UPDATE_INTIAL = "ON_UPDATE_INTIAL";
export const ON_UPDATE_SUCCESS = "ON_UPDATE_SUCCESS";
export const ON_UPDATE_FAIL = "ON_UPDATE_FAIL";