export const ON_BLOGS_DRAFTS_INITIAL_REQUEST = "ON_BLOGS_DRAFTS_INITIAL_REQUEST";
export const ON_BLOGS_DRAFTS_SUCESS = "ON_BLOGS_DRAFTS_SUCESS";
export const ON_BLOGS_DRAFTS_FAIL = "ON_BLOGS_DRAFTS_FAIL";

export const ON_FETCH_ALL_DRAFTS_INITIAL = "ON_FETCH_DRAFTS_ALL_INITIAL";
export const ON_FETCH_ALL_DRAFTS_SUCCESS = "ON_FETCH_ALL_DRAFTS_SUCCESS";
export const ON_FETCH_ALL_DRAFTS_FAIL = "ON_FETCH_ALL_DRAFTS_FAIL";

export const ON_FETCH_ONE_DRAFTS_INITIAL = "ON_FETCH_ONE_DRAFTS_INITIAL";
export const ON_FETCH_ONE_DRAFTS_SUCCESS = "ON_FETCH_ONE_DRAFTS_SUCCESS";
export const ON_FETCH_ONE_DRAFTS_FAIL = "ON_FETCH_ONE_DRAFTS_FAIL";

export const ON_DELETE_DRAFTS_INITIAL = "ON_DELETE_DRAFTS_INITIAL";
export const ON_DELETE_DRAFTS_SUCCESS = "ON_DELETE_DRAFTS_SUCCESS";
export const ON_DELETE_DRAFTS_FAIL = "ON_DELETE_DRAFTS_FAIL";

export const ON_UPDATE_DRAFTS_INTIAL = "ON_UPDATE_DRAFTS_INTIAL";
export const ON_UPDATE_DRAFTS_SUCCESS = "ON_UPDATE_DRAFTS_SUCCESS";
export const ON_UPDATE_DRAFTS_FAIL = "ON_UPDATE_DRAFTS_AIL";